name: ci

on:
  push:
    branches:
      - "**"
    tags:
      - "v*.*.*"

jobs:
  build-base:
    strategy:
      matrix:
        version: ["24.04"]
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64
          tags: |
            k3env/devcontainers:base-${{ matrix.version }}
            ghcr.io/k3env/devcontainers:base-${{ matrix.version }}
          build-args: |
            UBUNTU_RELEASE=${{ matrix.version }}
          file: images/Dockerfile.base
  build-php:
    strategy:
      matrix:
        version:
          [
            "5.6",
            "7.0",
            "7.1",
            "7.2",
            "7.3",
            "7.4",
            "8.0",
            "8.1",
            "8.2",
            "8.3",
            "8.4",
          ]
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64
          tags: |
            k3env/devcontainers:php-${{ matrix.version }}
            ghcr.io/k3env/devcontainers:php-${{ matrix.version }}
          build-args: |
            BASE_IMAGE=ghcr.io/k3env/devcontainers:base-24.04
            DC_VERSION=${{ matrix.version }}
            DC_PACKAGE=php
          file: images/Dockerfile.php
